# Generated by Django 3.1.6 on 2021-02-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_subnet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subnet',
        ),
    ]
