# Generated by Django 3.1.6 on 2021-03-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_subnet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subnet',
            options={'ordering': ['subnet_name']},
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='address_prefix',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='cidr',
        ),
    ]
