# Generated by Django 3.1.6 on 2021-03-04 13:52

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_auto_20210304_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='ipv4addr',
            field=netfields.fields.InetAddressField(default='0.0.0.0', max_length=39),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subnet',
            name='ipv6addr',
            field=netfields.fields.InetAddressField(default='::', max_length=39),
            preserve_default=False,
        ),
    ]
