# Generated by Django 3.1.6 on 2021-03-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0006_auto_20210304_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnet',
            name='ipv6addr',
        ),
    ]
