# Generated by Django 3.1.6 on 2021-03-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0007_remove_subnet_ipv6addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnet',
            old_name='ipv4addr',
            new_name='addr',
        ),
    ]
